vich_uploader:
    db_driver: orm

    mappings:
        device_config:
            uri_prefix: '%app.path.device_conf%'
            upload_destination: '%kernel.project_dir%/public%app.path.device_conf%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
